<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$sppcfw_available_hooks=apply_filters('sppcfw_available_hooks',array(
    ''=>'Choose a display location',
    'woocommerce_breadcrumb'=>'woocommerce_breadcrumb',
    'woocommerce_before_main_content' => 'woocommerce_before_main_content',
    'woocommerce_before_single_product' => 'woocommerce_before_single_product',
    'woocommerce_before_single_product_summary'=> 'woocommerce_before_single_product_summary',
    'woocommerce_single_product_summary' => 'woocommerce_single_product_summary',
    'woocommerce_simple_add_to_cart' => 'woocommerce_simple_add_to_cart',
    'woocommerce_before_add_to_cart_form' =>  'woocommerce_before_add_to_cart_form',
    'woocommerce_before_add_to_cart_button' =>  'woocommerce_before_add_to_cart_button',
    'woocommerce_before_add_to_cart_quantity' => 'woocommerce_before_add_to_cart_quantity',
    'woocommerce_before_quantity_input_field' => 'woocommerce_before_quantity_input_field',
    'woocommerce_after_quantity_input_field' => 'woocommerce_after_quantity_input_field',
    'woocommerce_after_add_to_cart_quantity' =>  'woocommerce_after_add_to_cart_quantity',
    'woocommerce_after_add_to_cart_button' => 'woocommerce_after_add_to_cart_button',
    'woocommerce_after_add_to_cart_form'=> 'woocommerce_after_add_to_cart_form',
    'woocommerce_product_meta_start'=>  'woocommerce_product_meta_start',
    'woocommerce_product_meta_end' => 'woocommerce_product_meta_end',
    'woocommerce_after_single_product_summary' => 'woocommerce_after_single_product_summary',
    'woocommerce_review_before' => 'woocommerce_review_before',
    'woocommerce_review_before_comment_meta' => 'woocommerce_review_before_comment_meta',
    'woocommerce_review_meta' => 'woocommerce_review_meta',
    'woocommerce_review_before_comment_text' => 'woocommerce_review_before_comment_text',
    'woocommerce_review_comment_text' => 'woocommerce_review_comment_text',
    'woocommerce_review_after_comment_text' => 'woocommerce_review_after_comment_text',
    'comment_form_before' => 'comment_form_before',
    'comment_form_top' =>  'comment_form_top',
    'comment_form_logged_in_after' => 'comment_form_logged_in_after',
    'comment_form' => 'comment_form',
    'comment_form_after' =>  'comment_form_after',
    'woocommerce_product_after_tabs' => 'woocommerce_product_after_tabs',
    'woocommerce_after_single_product' =>  'woocommerce_after_single_product',
    'woocommerce_after_main_content' => 'woocommerce_after_main_content',
    'woocommerce_variable_add_to_cart'=>'woocommerce_variable_add_to_cart',
    'woocommerce_before_variations_form'=> 'woocommerce_before_variations_form',
    'woocommerce_after_variations_table'=>'woocommerce_after_variations_table',
    'woocommerce_before_single_variation'=> 'woocommerce_before_single_variation',
    'woocommerce_single_variation'=>'woocommerce_single_variation',
    'woocommerce_after_single_variation'=>'woocommerce_after_single_variation',
    'woocommerce_after_variations_form'=> 'woocommerce_after_variations_form',
    'woocommerce_share'=>'woocommerce_share',
    'woocommerce_product_additional_information'=> 'woocommerce_product_additional_information',
    'woocommerce_grouped_product_list_before'=>'woocommerce_grouped_product_list_before',
    'woocommerce_grouped_product_list_before_quantity'=>'woocommerce_grouped_product_list_before_quantity',
    'woocommerce_grouped_product_list_after_quantity'=>'woocommerce_grouped_product_list_after_quantity',
    'woocommerce_grouped_product_list_before_label'=>'woocommerce_grouped_product_list_before_label',
    'woocommerce_grouped_product_list_after_label'=>'woocommerce_grouped_product_list_after_label',
    'woocommerce_grouped_product_list_before_price'=>'woocommerce_grouped_product_list_before_price',
    'woocommerce_grouped_product_list_after_price'=>'woocommerce_grouped_product_list_after_price',
    'woocommerce_grouped_product_list_after'=>'woocommerce_grouped_product_list_after',
    
));

